/**
 * Seed script: Creates 10 Ready_For_Shipping orders with paired invoices.
 * Purpose: Generate test data for the Logistics "Delivery Trip" feature.
 *
 * Usage:
 *   node seedReadyOrders.js
 *
 * Requirements: Active stores, products, and at least one user must exist in the DB.
 */

require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('./config/db');

const Order = require('./models/Order');
const Invoice = require('./models/Invoice');
const Store = require('./models/Store');
const User = require('./models/User');
const Product = require('./models/Product');
const Batch = require('./models/BatchModel');
const Role = require('./models/Role');

// ─── Helpers ──────────────────────────────────────────────────────────────────

const getRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];
const getRandomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;

const RECIPIENT_PHONES = [
  '0912345678',
  '0987654321',
  '0934567890',
  '0965432109',
  '0901234567',
];

// ─── Main ──────────────────────────────────────────────────────────────────────

const seedReadyOrders = async () => {
  await connectDB();
  console.log('Connected to DB. Starting Ready_For_Shipping order seed...\n');

  // 1. Fetch active stores
  const stores = await Store.find({ status: 'Active' });
  if (!stores.length) {
    console.error('ERROR: No active stores found. Please seed stores first.');
    process.exit(1);
  }
  console.log(`Found ${stores.length} active store(s).`);

  // 2. Find one user to act as "createdBy" — prefer Manager or StoreStaff
  const role = await Role.findOne({ roleName: { $in: ['Manager', 'StoreStaff'] } });
  if (!role) {
    console.error('ERROR: No Manager or StoreStaff role found. Please seed roles first.');
    process.exit(1);
  }
  const user = await User.findOne({ roleId: role._id });
  if (!user) {
    console.error(`ERROR: No user found with role '${role.roleName}'. Please seed users first.`);
    process.exit(1);
  }
  console.log(`Using user: ${user.email || user._id} (${role.roleName})`);

  // 3. Fetch all products
  const products = await Product.find({});
  if (!products.length) {
    console.error('ERROR: No products found. Please run seedProducts.js first.');
    process.exit(1);
  }
  console.log(`Found ${products.length} product(s).`);

  // 4. Fetch active batches and build a product → batch lookup
  const batches = await Batch.find({ status: 'Active' });
  const batchByProduct = {};
  batches.forEach((b) => {
    const key = b.productId.toString();
    if (!batchByProduct[key]) batchByProduct[key] = [];
    batchByProduct[key].push(b);
  });
  console.log(`Found ${batches.length} active batch(es).\n`);

  // 5. Build 10 order documents
  const orderDocs = [];
  for (let i = 0; i < 10; i++) {
    const store = getRandom(stores);

    // Delivery date: 2–14 days from now
    const deliveryDate = new Date();
    deliveryDate.setDate(deliveryDate.getDate() + getRandomInt(2, 14));

    // Pick 2–3 random products (shuffled)
    const shuffled = [...products].sort(() => Math.random() - 0.5);
    const selectedProducts = shuffled.slice(0, getRandomInt(2, 3));

    const items = selectedProducts.map((p) => {
      const quantity = getRandomInt(5, 20);
      const unitPrice = p.price;
      const subtotal = unitPrice * quantity;

      const item = { productId: p._id, quantity, unitPrice, subtotal };

      // Attach batch if one exists for this product
      const batch = batchByProduct[p._id.toString()]?.[0];
      if (batch) item.batchId = batch._id;

      return item;
    });

    const totalAmount = items.reduce((sum, it) => sum + it.subtotal, 0);

    orderDocs.push({
      storeId: store._id,
      createdBy: user._id,
      status: 'Ready_For_Shipping',
      requestedDeliveryDate: deliveryDate,
      address: store.address,
      recipientName: store.storeName,
      recipientPhone: getRandom(RECIPIENT_PHONES),
      items,
      totalAmount,
    });
  }

  // 6. Insert all orders (orderCode auto-generated by schema default)
  const insertedOrders = await Order.insertMany(orderDocs);
  console.log(`Inserted ${insertedOrders.length} order(s).`);

  // 7. Build one invoice per order
  const TAX_RATE = 10; // 10%
  const now = new Date();
  const dueDate = new Date(now);
  dueDate.setDate(now.getDate() + 30);
  const seedTimestamp = now.getTime();

  const invoiceDocs = insertedOrders.map((order, idx) => {
    const subtotal = order.totalAmount;
    const taxAmount = subtotal * (TAX_RATE / 100);
    const totalAmount = subtotal + taxAmount;

    return {
      invoiceNumber: `INV-SEED-${seedTimestamp}-${idx + 1}`,
      orderId: order._id,
      storeId: order.storeId,
      invoiceDate: now,
      dueDate,
      subtotal,
      taxRate: TAX_RATE,
      taxAmount,
      totalAmount,
      paymentStatus: 'Pending',
      paymentMethod: 'Cash',
      paidAmount: 0,
    };
  });

  // 8. Insert all invoices (manually set taxAmount/totalAmount since insertMany skips pre-save hooks)
  const insertedInvoices = await Invoice.insertMany(invoiceDocs);
  console.log(`Inserted ${insertedInvoices.length} invoice(s).\n`);

  // 9. Summary
  console.log('─'.repeat(70));
  console.log('  # │ Order Code              │ Total Amount (VND)');
  console.log('─'.repeat(70));
  insertedOrders.forEach((o, i) => {
    const line = `  ${String(i + 1).padStart(2)} │ ${o.orderCode.padEnd(23)} │ ${o.totalAmount.toLocaleString('vi-VN')}`;
    console.log(line);
  });
  console.log('─'.repeat(70));
  console.log(`\nAll ${insertedOrders.length} orders are now in status: Ready_For_Shipping`);
  console.log('They are ready to be assigned to a Delivery Trip in the Logistics module.\n');

  await mongoose.disconnect();
  console.log('Disconnected from DB. Seed complete.');
  process.exit(0);
};

seedReadyOrders().catch((err) => {
  console.error('Seeder failed:', err.message);
  process.exit(1);
});
